### ISSUE TITLE
Pubmed and PoA v2

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#23]
Graham: In thinking about Pubmed deposits for a PoA v2, one problem is the PoA XML does not specify a publication date.

So, let's say you published a PoA today Sept 17th, then supplied a v2 on Sept 18th, then the publication date at Pubmed would change from Sept 17th to Sept 18th. Maybe this doesn't matter, but I should check what date the HW site has and also which date TNQ uses as its publication date.

One way to solve this may be to query the Pubmed system, as we discussed, to see if the record already exists and use that publication date.

Any thoughts?

**Comment by gnott** [comment]
The chosen method to determine the published date of a PoA article at this time was to use the PubMed deposit history. This is stored in the S3 bucket in the folders used for the pubmed workflow. Each hour it checks for when an article is published, and so it has an accurate date for each article since about September 2014.
