### ISSUE TITLE
Individual members of group authors not getting delivered to PubMed

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#28]
Hi Graham

We've found for 02935 that the group authors listed in the final PoA xml have not been converted and sent to PubMed.

This can be found in commit:
https://github.com/elifesciences/elife-pubmed-feed/commit/4871b6d60a5d4d10ec2e27f5a5d5f99876c32fad

The eLife xml is:
https://github.com/elifesciences/JATs-xml/commit/63595d71d9bab4ba342172643cd4e8aea9173c2e

Can we add this in ASAP?

Sorry, I did not realise this was missed off.
M

**Comment by gnott** [comment]
My understanding is these are contributors linked to a group author by a ``contrib-id``? E.g.

```
<contrib-id contrib-id-type="group-author-key">group-author-id1</contrib-id>
```

02935 as an example, I don't think the data of the actual group author's contributors are included. For this I may need to punt it back to James for more query development.

**Comment by Melissa37** [comment]
This is a VoR stage item. EJP does not store this data, so we cannot do it at PoA, but the final xml TNQ produces contains it where present at VoR stage.

**Comment by gnott** [comment]
I understand now, it's the VoR XML to Pubmed issue. I will take this on!

**Comment by Melissa37** [comment]
Fab thanks! Lets chat about timelines on Thurs

**Comment by gnott** [comment]
In parsing the XML file, only these were extracted as contributors

```
<contrib contrib-type="author">
```

Individual contributors as part of a group are specified as

```
<contrib contrib-type="author non-byline">
```

These ``non-byline`` authors will be added to the end of the contributor list. 

Crossref XML generation already only includes ``contrib-type="author"`` contributors. 

Pubmed XML generation will be set to include both types, ``contrib-type="author"`` and ``contrib-type="author non-byline"``.

**Comment by Melissa37** [comment]
Hi there This is fixed now isn't it? Closing the ticket.
M

**Comment by gnott** [comment]
Sitting down today, I resolve some errors with existing test cases and trying to confirm the strategy was sound I was following. The code change is in PR https://github.com/elifesciences/elife-pubmed-xml-generation/pull/44. 

It is an improvement, I think, to remove the `group_author_contrib_types` configuration file value, because it was not working and was going to cause more trouble than instead relying on contributor `group_author_key` attributes that we are already setting when parsing the article XML.

I feel confident with the test coverage and the impact of the change, it's ready to merge and deploy, which I will move to do today. We can adjust or rollback the week of January 24th if we observe any errors.
