### ISSUE TITLE
< characters, needs more investigation and re-coding 14003 as PubMed breaking on it

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#37]
From Graham: The last time we saw this I thought we were going to look at the possibility to move from &#x003C; back to &lt; for the < characters. We had good support for that. I don't think it was a final decision though, because you mentioned &#x003C; was part of the new procedure you'd devised.
I was going to have to rework how the text is parsed in order to try and fix this. &#x003C; comes through as a < character, natively, and and it conflicts with the tag recognition logic for finding <italic>, <sup> tags, etc.
I can look at writing an automated test against this new tagging scheme, and then try and rewrite the way these nested tags are dealt with.
Graham to look at this week

**Comment by gnott** [comment]
The above redone to show the proper characters,

From Graham: The last time we saw this I thought we were going to look at the possibility to move from &amp;#x003C; back to &amp;lt; for the < characters. We had good support for that. I don't think it was a final decision though, because you mentioned &amp;#x003C; was part of the new procedure you'd devised.
I was going to have to rework how the text is parsed in order to try and fix this. &amp;#x003C; comes through as a < character, natively, and and it conflicts with the tag recognition logic for finding <italic>, <sup> tags, etc.
I can look at writing an automated test against this new tagging scheme, and then try and rewrite the way these nested tags are dealt with.
Graham to look at this week

**Comment by Melissa37** [comment]
http://jira.elifesciences.org:8080/browse/ELPP-926
