### ISSUE TITLE
Conflict of Interest (COI) Statements

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#44]
If a published article includes a Conflict of Interest (COI) Statement, please include it in your XML citation data submission to PubMed. These COI statements should be provided in a new element: . This element occurs after the and tags, and before the .

These COI statements can also be added to citations in PMDM. The Conflict of Interest field appears in the Abstract section, just below Copyright Information.

**Comment by gnott** [comment]
I believe this is put into the ``<CoiStatement>`` tag in deposits and requires using schema version 2.7.

**Comment by gnott** [comment]
This was a little more complicated than I expected. 

Only one ``<CoiStatement>`` tag is allowed for each PubMed deposit, which is not such a surprise.

A contributor may have more than one conflict of interest, potentially, so I changed the parsing and Contributor object to have a list of conflict values.

The conflict of interest values on their own do not always make sense when they are separated from the contributor, and is why the conflict is attached to an author and not to the entire paper itself.

Some conflict values have something like "The authors declare that no competing interests exist.", and due to how the conflict of interest is attached to an author, these can end up being duplicated if they're not omitted. I've added a configuration variable to ignore certain values from inclusion if they contain certain phrases, as specified by the journal's configuration.

I created a very simple name initial function, which will just take the first character from the given_names and surname, if present, to prepend to the conflict statement.

Then, all the conflict statements are joined together as a comma separated string, to be added to the single PubMed schema tag.

I can see one issue with this logic now I'm describing it, is if we only have the value of "The authors declare that no competing interests exist." and that is on the ignore list, then we will end up omitting a ``<CoiStatement>`` entirely. @Melissa37 how important is it if there is always a ``<CoiStatement>`` even when no authors have declared a conflict of interest, and the ``<CoiStatement>`` would only be present when an author has declared a conflict of interest?

**Comment by Melissa37** [comment]
If 2 authors share a statement their initials are grouped at the start (comma separated) followed by the text.
Therefore, in eLife new XML where there is no conflict:  <p>No competing interests declared</p>
The authors who are associated with this footnotes have their initials at the start (comma separated), followed by this text.
