### ISSUE TITLE
<replaces> tag for versions

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#58]
This is a new feature.
Have questions out with PubMed about this:
Can we use it to update our archive with funding metadata
Can we use it to update versions of VoR that are past the  [PubMed – as supplied by publisher] stage

**How to tag a new version**

To submit new version of an existing PubMed citation, create an XML file using <Replaces> tags referring to the PMID of the prior version. Assign a new VersionID and VersionDate.

Here is a sample section of an XML file showing the VersionID, VersionDate, and Replaces tagging:

```
<ArticleSet>
<Article VersionID="2" VersionDate="2009/10/01">
<Journal>
<PublisherName>Public Library of Science</PublisherName>
<JournalTitle>PLoS Curr</JournalTitle>
<Issn>2157-3999</Issn>
<Volume>1</Volume>
<PubDate PubStatus="epublish">
<Year>2009</Year>
<Month>9</Month>
<Day>29</Day>
</PubDate>
</Journal>
<Replaces IdType="pubmed">20029614</Replaces>
<ArticleTitle>The severity of pandemic H1N1 influenza in the United States, April-July 2009</ArticleTitle>
```

Correcting errors in versioned citations

A versioned citation can be updated to correct errors when in status [PubMed – as supplied by publisher]. Create a Replaces file using <Replaces> tags but use the same VersionID as in the existing version that you are replacing. Do not assign a new VersionID.

Searching and retrieving using versions

Only the most recent version of a citation will be indexed and returned in a PubMed search. The content, e.g., author names, abstract terms, from previous versions will not be included in the PubMed indices. For example, if an author name has been removed from the author list in the most recent version, a PubMed search for that author name will not retrieve the citation. The prior version(s) of a citation are accessible via links on the abstract display of the most recent version.

Search for a specific version of a citation by entering a PMID.version (e.g., 20029611.1) in the PubMed search box. To search for multiple versions of a citation at once, use a Boolean OR (e.g., 20029611.1 OR 20029611.2). Search for all versions of a citation by entering the PMID followed by .* (e.g., 20029611.*) in the PubMed search box.

Retrieve a specific version by explicitly adding the version number after the PMID in the URL, e.g., https://www.ncbi.nlm.nih.gov/pubmed/20029611.1. Only a single version can be retrieved at a time using this method.

Dates

PubMed will set the DateCreated for the new version to the date the citation is added to PubMed. Versioned citations will follow the standard Entrez Date assignment rules.

**Comment by Melissa37** [comment]
From PubMed:
We added versioned citations to PubMed several years ago. Since NLM has a narrow definition of a version (revisions, scientific updates, and updates of reviews), the number of versioned PubMed records is very small.  
 
Can you provide some examples of the post-publication updates to the metadata? Corrections to author names, for instance, should be made in PMDM. Submitting new versions of the citation using the version tagging as described in the Help would not be appropriate in these cases.
We accept Replaces files for ahead of print citations and data in the following fields, regardless of the citation’s status in PubMed:
 
AuthorList (includes Author, Affiliation, Identifier)
InvestigatorList (includes Investigator, Affiliation, Identifier)
Pagination
ELocationID
OtherAbstract
PII
DOI
 
Our loader will compare the content of these fields in the Replaces file with the existing PubMed citation and only modify the content if it is different. We don’t currently accept Replaces files to add/update grant information.

**Comment by gnott** [comment]
Thank-you for the additional detail. My take on this as I read it now is we could shelve adding any version support until a later date.

It would not solve any immediate fixes for eLife articles. For example,

1. The differences between a PoA article and a VoR article are not considered a new version. We already use the "aheadofprint" date for PoA articles, which are later replaced with the VoR.

2. Appending additional details to older PubMed records, such as grant information, is not accepted when depositing an article again using the ``<Replaces>`` tag. This is unrelated to article versions (since there would be only one article version, and it would replace data in that one version), but it is related to the answers above, depositing a new version which is not really a new version, and just to add more grant details, does not seem to fit how new versions are supposed to work.

I will assign to you @Melissa37 if you would like to provide feedback on my interpretation and whether we should ignore depositing multiple versions of an article to Pubmed, instead relying on the existing logic of the ``<Replaces>`` tag in deposits and the ability to overwrite basic metadata if it is incorrect.

**Comment by Melissa37** [comment]
Agree with you! M
